export const products = [
    {
      id: "1",
      name: "iPhone 15 Pro",
      description:"iPhone 15 Pro",
      price: 1199,
      quantity: 2,
      in_stock: true,
      img: "https://example.com/images/iphone15pro.jpg",
      category:"Cellular",
    },
    {
      id: "2",
      name: "Samsung Galaxy S24",
      description:"Samsung Galaxy S24",
      price: 999,
      quantity: 5,
      in_stock: true,
      img: "https://example.com/images/galaxyS24.jpg",
      category:"Cellular",
    },
    {
      id: "3",
      name: "MacBook Pro 16”",
      description:"MacBook Pro 16”",
      price: 2499,
      quantity: 1,
      in_stock: true,
      img: "https://example.com/images/macbookpro16.jpg",
      category:"Computers",
    },
    {
      id: "4",
      name: "Sony WH-1000XM5 Headphones",
      description:"Sony WH-1000XM5 Headphones",
      price: 399,
      quantity: 3,
      in_stock: true,
      img: "https://example.com/images/sonywh1000xm5.jpg",
      category:"Audio",
    },
    {
      id: "5",
      name: "iPad Air 6",
      description:"iPad Air 6",
      price: 699,
      quantity: 4,
      in_stock: true,
      img: "https://example.com/images/ipadair6.jpg",
      category:"iPads",

    },
    {
      id: "6",
      name: "Apple Watch Ultra 2",
      description:"Apple Watch Ultra 2",
      price: 799,
      quantity: 2,
      in_stock: false,
      img: "https://example.com/images/applewatchultra2.jpg",
      category:"Watches",
    },
    {
      id: "7",
      name: "Google Pixel 9",
      description:"Google Pixel 9",
      price: 899,
      quantity: 3,
      in_stock: true,
      img: "https://example.com/images/pixel9.jpg",
      category:"Cellular",
    },
    {
      id: "8",
      name: "Dell XPS 13",
      description:"Dell XPS 13",
      price: 1399,
      quantity: 2,
      in_stock: false,
      img: "https://example.com/images/dellxps13.jpg",
      category:"Computer",
    },
    {
      id: "9",
      name: "Nintendo Switch OLED",
      description:"Nintendo Switch OLED",
      price: 349,
      quantity: 7,
      in_stock: true,
      img: "https://example.com/images/switcholed.jpg",
      category:"Consoles",
    },
    {
      id: "10",
      name: "Bose SoundLink Revolve+ II",
      description:"Bose SoundLink Revolve+ II",
      price: 299,
      quantity: 5,
      in_stock: true,
      img: "https://example.com/images/bosesoundlink.jpg",
      category:"Audio",
    },
  ];
  